name: D&V STORE Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать файлы
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Запустить синхронизацию Apple Avenue
        run: python sync.py

      - name: Сохранить обновления
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add products.json

          if git diff --cached --quiet; then
            echo "Изменений нет"
          else
            git commit -m "Автообновление каталога D&V STORE"
            git push
          fi
